name: ThunderCraftCore
version: 1.1
author: Polo
main: me.polo.Core.Core
api-version: 1.17

commands:
  challenges:
  ice:

  clearchat:
    permission: chat.clear
  heal:
    aliases: h
    permission: heal.use
  feed:
    aliases: f
    permission: feed.use
  freeze:
    permission: freeze.use
  unfreeze:
    permission: freeze.use

  trade:
